[build]
  command = "npm run build && npm run export"
  publish = ".next"
  base = "/"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[plugins]]
  package = "@netlify/plugin-nextjs"
